# Azure Tester
trigger: 
- master # Triggers when on master. Either pr or push

resources:
  containers:
  - container: wpilib2020
    image: wpilib/roborio-cross-ubuntu:2020-18.04
  - container: raspbian
    image:  wpilib/raspbian-cross-ubuntu:10-18.04
  - container: bionic
    image: wpilib/aarch64-cross-ubuntu:bionic-18.04

jobs:

- job: linux
  pool:
    vmImage: 'Ubuntu 21.04'
  container: bionic
  steps:
  - template: azure-init.yml
  - script: git submodule update --init
  - script: git submodule update --remote -f
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx4096m'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'clean generateFramework build'
      options: '-Pno-roborio -PazureBuild -Pforce -Ptoolchain-optional-roboRio'

- job: windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - template: azure-init.yml
  - script: git submodule update --init
  - script: git submodule update --remote -f
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx4096m'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'clean generateFramework build'
      options: '-Pno-roborio -PazureBuild -Pforce -Ptoolchain-optional-roboRio'

- job: mac
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - template: azure-init.yml
  - script: git submodule update --init
  - script: git submodule update --remote -f
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx4096m'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'clean generateFramework build'
      options: '-Pno-roborio -PazureBuild -Pforce -Ptoolchain-optional-roboRio'